env:
  browser: true
  es6: true
  node: true
  webextensions: true
extends: 'eslint:recommended'
globals:
  Chart: true
  chrome: true
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  curly:
    - error
    - all
  eqeqeq:
    - error
    - smart
  block-spacing:
    - error
  brace-style:
    - error
  camelcase:
    - error
  array-bracket-spacing:
    - error
  func-call-spacing:
    - error
  max-depth:
    - error
  new-cap:
    - error
  new-parens:
    - error
  no-lonely-if:
    - error
  no-mixed-spaces-and-tabs:
    - error
  no-multiple-empty-lines:
    - error
  no-trailing-spaces:
    - error
  space-before-function-paren:
    - error
    - never
  space-before-blocks:
    - error
  space-in-parens:
    - error
  no-console: off
